### ISSUE TITLE
Rename `weight` by `grid_fee` for price adjustments

### ISSUE THREAD

**Issue by j-ti** [BESTenergytrade/simply#100]
I noticed also in fair_market it is called `weight`, but the grid_fee is not necessarily equal to the weight, the weight is the network-graph weights and the grid_fee is adjusted by the weight factor which is only 1 as a default

_Originally posted by @j-ti in https://github.com/BESTenergytrade/simply/pull/99#discussion_r871429990_

**Comment by dog-ball** [comment]
closes #100
