### ISSUE TITLE
ModuleNotFoundError when running Pytest with fresh install of simply

### ISSUE THREAD

**Issue by dog-ball** [BESTenergytrade/simply#102]
Both myself and Frieda have experienced a ModuleNotFoundError when trying to run pytest on a fresh install of simply after making sure the correct modules have been installed (using other simply functionality like main.py works fine).

**My error:**
ModuleNotFoundError: No module named 'matplotlib'

**Frieda's error:**
ModuleNotFoundError: No module named 'pathlib'

**Screenshot of error message:**
![Screenshot 2022-05-19 at 15 16 57](https://user-images.githubusercontent.com/73889326/169315794-90d6abc7-9eda-4803-ab44-89bdba46774c.png)

**Comment by j-ti** [comment]
@dog-ball @FC4R Can you verify the correct virtual environment was used? While using pytest, it might use another python version, as it is not part of the `requirements.txt` (as it is not part of the module itself), but we can create a test requirement file as proposed in #85, which currently only would add pytest itself. The current solution in the github workflow was to install requirements and install pytest on top.

**Comment by dog-ball** [comment]
I just tried again. The first time I activated the virtual environment, installed `requirements.txt` and then installed pytest on top and i recieved the same error shown above. I then wiped everything and redownloaded a fresh simply and activated the virtual environment and added pytest into the `requirements.txt` and got the same error again 🫤

**Comment by j-ti** [comment]
but is the python version stated in the error message the same of the virtual environment?

**Comment by j-ti** [comment]
[f32889e](https://github.com/BESTenergytrade/simply/commit/f32889e5d0dfd4446cec0f586546c7b76803d9fc)
@dog-ball As I said, actually pytest is not part of simply so it should not be a requirement
a solution would be to have a specific requirement for testing

**Comment by dog-ball** [comment]
Okay - like a 'testing_requirements.txt' file with pytest?

**Comment by j-ti** [comment]
rather requirement.txt within the test folder

**Comment by j-ti** [comment]
also I changed the command line to `python -m pytest `which also would solve the other issue with activate venv twice

**Comment by j-ti** [comment]
> 
when adding another requirement please also add the command `pip install -r tests/requirements.txt` to the readme for the testing

**Comment by dog-ball** [comment]
Yes - no problem :)
