### ISSUE TITLE
Fair/ Best Market shows unexpected behaviour

### ISSUE THREAD

**Issue by PaulScheerRLI** [BESTenergytrade/simply#162]
Symmetric clusters without gridfees and symmetric bids and ask dont produce the same clearing prices. See linked branch with test case in test_market_fair.py

**Comment by FC4R** [comment]
When printing the matches it can be seen that first cluster0 is matched and afterwards cluster1 i.e. the cheaper asks are already gone when it's cluster1's turn. 
We @j-ti, @dog-ball  agreed that disputed matches should go to the higer price and if same price than to lower grid fees
Is that already implemented in another branch?
Remarks:
1. higher price is, as @PaulScheerRLI pointed out not the correct criteria but it should be higher ask-price
2. maybe a third criterion should be "same cluster" in case grid fees are the same (which they are supposed to be (on the same grid level)  if no grid restrictions  exist)
?

**Comment by j-ti** [comment]
> We @j-ti, @dog-ball agreed that disputed matches should go to the higer price and if same price than to lower grid fees
> Is that already implemented in another branch?

Yes on https://github.com/BESTenergytrade/simply/tree/feature/resolve_disputed_matches there are still merge conflicts.

I will resolve those now and maybe I can merge it today (however, it might need more tests)

**Comment by j-ti** [comment]
> I will resolve those now and maybe I can merge it today (however, it might need more tests)

I might rather merge this branch into the one just named above to resolve both topics together. @FC4R

**Comment by FC4R** [comment]
@j-ti it both concernes only market_fair.py (?) so I think it makes sense to think about it together...

**Comment by j-ti** [comment]
Test included and is resolved
