### ISSUE TITLE
Stop in merge-able development

### ISSUE THREAD

**Issue by PaulScheerRLI** [BESTenergytrade/simply#169]
Recent developments like the introduction of batteries and agents with strategies were done in wip branches. Therefore these features are not available in the main development branch. Small branches should take necessary features of these draft branches, so they can be merged into main asap.

**Comment by PaulScheerRLI** [comment]
typo of wip: work in progress. The issue has been discussed with j-ti. The current work on battery implementation into dev as well as actor strategies is part of resolving that issue.

**Comment by FC4R** [comment]
awesome

**Comment by j-ti** [comment]
To be checked what is already merged or about-to-be-merged from feature/battery content and what is not -> making PRs or issues
