### ISSUE TITLE
Example scenario is depricated

### ISSUE THREAD

**Issue by j-ti** [BESTenergytrade/simply#176]
it seems, that `python main.py examples/config_examples.txt` does not run through, as `simply.scenario.load()` misses the battery argument. when Adding None, the schedule becomes wrong. Maybe schedule can be deleted from csv files.

**Comment by j-ti** [comment]
Battery out of range assertion error arises within `battery.charge` as part of the `Actor.next_time_step()`

**Comment by j-ti** [comment]
> Battery out of range assertion error arises within `battery.charge` as part of the `Actor.next_time_step()`

this part is solved

**Comment by FC4R** [comment]
Can this be closed?
