### ISSUE TITLE
possible inconcistencies with build_scenario

### ISSUE THREAD

**Issue by FC4R** [BESTenergytrade/simply#190]
- [x] use of loads_dir.csv not clear
- [x] a scenario should only be build for given time span in config.txt 
- [ ] line 122 not correct
- [ ] lines 115/116 not clear
- [x] pv should be renamed to production
- [x] #213
- [x] does normalization belong in create_actor_from_config method? We need to find consistent way where data manipulation takes place and how it is controlled
- [x] same for weight factors

**Comment by j-ti** [comment]
closed in favor of new issues
