### ISSUE TITLE
Actor creates orders with Nan energy

### ISSUE THREAD

**Issue by j-ti** [BESTenergytrade/simply#193]
In case actor reaches end of time series, it will create an order with an energy and order type of np.nan.
Instead order should not be generated (a warning could be raised if actually data is missing)

**Comment by PaulScheerRLI** [comment]
I think an exception should be thrown, since not just order generation will not be possible but also handling of battery/schedule since most like the schedule is nan as well.

**Comment by j-ti** [comment]
I also think that an exception can be thrown, but maybe it is helpful if additionally a warning is raised already when an order is generated with a NaN order type and energy within the actor.
