### ISSUE TITLE
Fix erroneous creation of plots

### ISSUE THREAD

**Issue by TabeaMaria** [BESTenergytrade/simply#207]
On branch main-workflow: 
After cloning the repository and running build_scenario.py for the first time one network-plot and one empty timeseries plot are shown. With every other run of build_scenario.py two different network plots are shown + the correct timeseries plot.
--> Tasks: 1) Reduce number of network-plots to one plot. 2) Fix empty plot problem

**Comment by FC4R** [comment]
If I run build_scenario there is an error massage that I need to provide an project_dir. If I run build_scenario on projects/example_projects/example_project (with no scenario folder existing) I receive two correct network plots and after this one time series plot... can you confirm?

**Comment by FC4R** [comment]
The problem has something to do with scenario.py calling power_network.to_image(dirpath) in line 275. If this commented out plots appear as expected. So I guess that in power_networkt.py from line 112 the network is stored in fig and than plotted once plt.show() is called in scenario.py line 306. A fix might be to clear fig after to_image was executed.

**Comment by j-ti** [comment]
solved see commit above
