### ISSUE TITLE
branch feature/best_matching: incorrect matching

### ISSUE THREAD

**Issue by TabeaMaria** [BESTenergytrade/simply#219]
On branch "feature/best_matching" matching with market_type "fair" partly does not work correctly with actor strategy 1 and linear pricing. Even though residentials could be matched with each other they are sometimes matched with the MarketMaker instead. The same behaviour can be observed with actor strategy 2 and linear pricing.

### Examples:
- 3 actors on 2 clusters, all with load, PV and battery
- actor strategy: 1
- pricing strategy: linear
- weight_factor: 0.003
- default_grid_fee = 0.01

**Example 1:**
Orders:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/f4dc6bbf-4f09-4ef1-9f2b-feee73307f15)
Matches:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/674185cb-a055-449b-85f4-70cbf161f35c)

**Example 2**:
Orders:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/264ca9a6-bd76-48d3-8c82-d64e3de6f131)
Matches:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/1ad5ea72-acec-41a3-ae6e-86786b860bcd)
Note: MarketMaker prices are 0.045, not 45

**Comment by j-ti** [comment]
resolved see `test_update_clearing_cluster_issue220` and `test_update_clearing_cluster_issue220_b` in ` tests/test_market_fair.py`
