### ISSUE TITLE
branch feature/best_matching: "Matched energy does not match planned energy."

### ISSUE THREAD

**Issue by TabeaMaria** [BESTenergytrade/simply#220]
On branch "feature/best_matching" matching with market_type "fair" partly does not work correctly with actor strategy 0. 
Problems:
- The planned amount of energy to be traded (orders) does not always match the amount of energy actually traded (matches). _UserWarning: Matched energy does not match planned energy. warnings.warn("Matched energy does not match planned energy.")_
- Incorrect matching

### Examples:
3 actors in 2 clusters, all with load and PV
actor strategy: 0
weight_factor: 0.003
default_grid_fee = 0.01

**Example 1:**
Orders:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/4448af2e-fad3-427d-960b-2e104b345240)

Matches:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/e29287bc-cde6-492c-9c02-38f29549ddd0)

**Example 2:**
Orders:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/4c4202d2-c0d8-4c45-bbeb-a31058b6c584)

Matches:
![image](https://github.com/BESTenergytrade/simply/assets/73853371/6966d0cb-0f5b-40a4-b8c5-ccc4ea2a0b5e)

**Comment by j-ti** [comment]
Example 1:
A major issue is, in the current algorithm, that order of residential_2 can be matched in its own cluster 1 with residential_3 at a clearing price of 0.03659, and the rest 26 energy_units can be matched in cluster 0 with residential 1 at a clearing price of 0.05659 (as bidding volume is bigger than the ask volume - other than in cluster 1 -, the market maker ask prices are setting the clearing price in this case).
However the profit for residential_2 order units is higher in cluster 1 (despite the additional grid_fees). Consequently, in the iteration the total order of residential_2 is matched in cluster 1 and non in cluster 0, while this changes the clearing price in cluster 1 as now also here we have bidded energy units that cannot be matched locally, so the market maker ask is matched and becomes price setting to 0.05659.

So for this case it is unclear what the expected behavior should be. I will concentrate on a solution, so that this clearing price toggling does not happen by the already envisioned change regarding grid_fees being partitioned onto the total clearing volume so that their effect on the clearing price is more smooth

**Comment by j-ti** [comment]
@FC4R should this be expected for Example 1? (i.e. as matching residential_2 from cluster 1 in cluster 0 with a higher profit than within its own cluster would lead the same profit in its own cluster, due to a changing clearing price which now also regards the market maker order. Further should the clearing price be 0.03659 or also 0.05659? This last question has to be reevaluated when changing to grid_fee partitioning method)
![grafik](https://github.com/BESTenergytrade/simply/assets/56872869/cad1b086-48f3-426b-a17a-d688e82d2abe)

**Comment by j-ti** [comment]
Von Paul:
![image](https://github.com/BESTenergytrade/simply/assets/56872869/25184c96-7964-45d2-a265-dfc79763c155)
> das sind die order.
> Das resultierende matching "finde ich allerdings richtig"
> seller_c1_2 sells 0.21 to buyer_c0_1 for 0.05
> seller_c1_2 sells 0.06 to buyer_c1_3 for 0.05
> seller_MM sells 0.16 to buyer_c0_1 for 0.05
> seller_MM sells 0.01 to buyer_c1_3 for 0.05
> c1_3 wird fast ausschließlich durch den lokalen erzeuger gedeckt. alles wird gematched. seller c1_2 verkauft seinen gesamten strom zum marktwert von 0.05 der durch den matchmaker gesetzt wird
> test_update_clearing_cluster_issue220(self): finde ich die erklärung von dir auf github auch sehr passend.
> Für einen markt mit clearing price sollte aus meiner sicht (annährend da diskrete simulation) gelten, dass wenn der MarketMaker in den Markt involviert ist stets der MM Clearing price + grid fee entstehen muss. Dies ist positiv für die Energieerzeuger wenn sie günstiger produzieren da so ihre marge hoch ist. steigende erzeugung soll den MM aus dem Markt "treiben", bei EE überfluss ist der MM nicht mehr im Markt involviert und die lokalen preise wirken sich auch auf den ClearingPrice aus

Ich kann dieses Matching Resultat auch verstehen. Was einem direkt auffällt ist das hiermit mehr grid fees als nötig entstehen, da tatsächlich ja gar keine Energie aus dem Vorgelagerten Netz bereitgestellt werden muss, weil es bilanziell bereits lokal ausgeglichen wird ... Das ist aber eigentlich auch so im Matching Algorithmus angelegt, da wir sonst auch einfach hierarchisch entlang des Graphen matchen könnten. 

Der Vorteil unseres Algorithmus wäre dann, dass es nicht starr lokal gematched wird, sondern von den gridfees und ggf. hohen Differenzen von lokalen Clearing Preisen abhängig ist. Diese lokal-differenzierten clearing preise werden erst richtig zum Tragen kommen, wenn es entweder Lokale Überproduktion gibt und wenn die grid fees sich nicht als price rate sondern als grid_fee / clearing_volume auf die Clearing Menge aufgeteilt wird.

**Comment by PaulScheerRLI** [comment]
two issues might remain in the adjustment loop at the end
1. Asks show profit of zero although they are not matched. This can happen in cases where the many asks have the same price == clearing price
2. Asks should be moved to a different cluster if their profit remains the same, but matched energy increases. This check was removed, because it was not working as intended

**Comment by FC4R** [comment]
Hi, ich muss mir das das oben nochmal ansehen habe aber glaube ich ein Problem verstanden/entdeckt, dass erstmal noch nicht adressiert wird, oder?
folgende Situtation:
bid_cluster
---------------
bid_hightest      ask_lowest
bid_high            ask_low
bid_medium      ask_medium
--------------------------------- clearing price mit ask_low und ask_medium: medium price
bid_low             ask_high
                         ask_higher

sagen wir ask_low und ask_medium können beide in einem anderen cluster besser (mit mehr Profit) gematcht werden. Wenn aber aks_low aus dem cluster raus ist könnte ask_medium mit clearing price bid_high gematch werden und hätte hier den höchsten Profit. Es kommt also nicht nur darauf an ob ask_medium in dem cluster bleibt sondern auch ob alle anderen drinnen bleiben... Die einzige Lösung die mir dazu eingefallen ist ist leider eine Optimierung :( ? Oder habt ihr noch einen guten Sortieralgorithmus in Petto?

**Comment by PaulScheerRLI** [comment]
das ist in dem beispiel nicht ganz richtig. wenn ask_low in ein anderes cluster geht bekommt, ask_medium dadurch nicht einen höheren profit. Das ask_medium in beiden fällen den clearing_price setzt wird ask_medium in gezeigtem cluster 0 Profit machen. wenn ask_medium ins andere cluster wechselt, kann aber auch ask_high mit bid_high gematched werden. in diesem fall hätte die umverteilung der asks zwar zu einem höheren clearing price geführt, aber vielleicht auch zu mehr gematchter energie. Dabei kommt es auf die preisverteilung im "anderen" cluster an, im speziellen ob ask_low und ask_medium andere asks aus dem clearing verdrängen oder nicht

**Comment by FC4R** [comment]
Du hast recht, ich hatte (warum auch immer) den Denkfehler, dass die bids preissetzend wären 😵‍💫

**Comment by FC4R** [comment]
Ich fin 

> Von Paul nach Fix [e6cf25f](https://github.com/BESTenergytrade/simply/pull/200/commits/e6cf25f5b4349cb5bf8a35d64a01710e40581eaf): ![image](https://private-user-images.githubusercontent.com/56872869/296704447-25184c96-7964-45d2-a265-dfc79763c155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTAzODcsIm5iZiI6MTcwNTMxMDA4NywicGF0aCI6Ii81Njg3Mjg2OS8yOTY3MDQ0NDctMjUxODRjOTYtNzk2NC00NWQyLWEyNjUtZGZjNzk3NjNjMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjgyNGNhN2UxOWE1NWNlMjU3NTIwZjZhYWM5Y2M2MjU5ODkxNWYwOTkyM2U5MjA4NTg5M2E2YjNmMzVkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyhRxTOfL8vT_NMNPniY6_WYPgj5yOxdDyBAyeH7HKY)
> 
> > das sind die order.
> > Das resultierende matching "finde ich allerdings richtig"
> > seller_c1_2 sells 0.21 to buyer_c0_1 for 0.05
> > seller_c1_2 sells 0.06 to buyer_c1_3 for 0.05
> > seller_MM sells 0.16 to buyer_c0_1 for 0.05
> > seller_MM sells 0.01 to buyer_c1_3 for 0.05
> > c1_3 wird fast ausschließlich durch den lokalen erzeuger gedeckt. alles wird gematched. seller c1_2 verkauft seinen gesamten strom zum marktwert von 0.05 der durch den matchmaker gesetzt wird
> > test_update_clearing_cluster_issue220(self): finde ich die erklärung von dir auf github auch sehr passend.
> > Für einen markt mit clearing price sollte aus meiner sicht (annährend da diskrete simulation) gelten, dass wenn der MarketMaker in den Markt involviert ist stets der MM Clearing price + grid fee entstehen muss. Dies ist positiv für die Energieerzeuger wenn sie günstiger produzieren da so ihre marge hoch ist. steigende erzeugung soll den MM aus dem Markt "treiben", bei EE überfluss ist der MM nicht mehr im Markt involviert und die lokalen preise wirken sich auch auf den ClearingPrice aus
> 
> Ich kann dieses Matching Resultat auch verstehen. Was einem direkt auffällt ist das hiermit mehr grid fees als nötig entstehen, da tatsächlich ja gar keine Energie aus dem Vorgelagerten Netz bereitgestellt werden muss, weil es bilanziell bereits lokal ausgeglichen wird ... Das ist aber eigentlich auch so im Matching Algorithmus angelegt, da wir sonst auch einfach hierarchisch entlang des Graphen matchen könnten.
> 
> Der Vorteil unseres Algorithmus wäre dann, dass es nicht starr lokal gematched wird, sondern von den gridfees und ggf. hohen Differenzen von lokalen Clearing Preisen abhängig ist. Diese lokal-differenzierten clearing preise werden erst richtig zum Tragen kommen, wenn es entweder Lokale Überproduktion gibt und wenn die grid fees sich nicht als price rate sondern als grid_fee / clearing_volume auf die Clearing Menge aufgeteilt wird.

- Wie sind denn die Netzentgelte in dem Beispiel? 0.01 zum MM , oder? aber zwischen den clustern?
- Nach einer neu einzuführenden Rechnung sollte der Clearing Preis in cluster 1 ca. 0.0414ct betragen, weil die 0.01 grid fee ja nur auf ca. 14% der gehandelten Energie anfallen?!
-

**Comment by j-ti** [comment]
Es gelten die grid_fees wie im Beispiel von Tabea also `weight_factor: 0.003` (zwischen Cluster 0 und 1) `default_grid_fee = 0.01` (MarketMaker)

**Comment by PaulScheerRLI** [comment]
ich bin mir nicht sicher ob es funktioniert die grid fee einfach über den clearing price zu averagen. 
Beispiel Bid Cluster 1
Matches mit je einer energieeinheit
Bid Price, Ask Price, Included_Grid fee
5, 1.0, 0.0
4, 2.5, 0.0
3, 3.0, 2.4
das dritte match wird durch das teure Netzentgelt dominiert. Die average grid fee wäre hier 0.8 = 1/3 * 2.4
wenn jetzt der clearing price auf 
3- 0.8 = 2.2
gesetzt wird, reicht das nicht um den ask von 2.5 zu bezahlen. Wie wäre hier das vorgehen. aus sicht der lokalen akteure wirken sich dann externe akteure mit hohem netzentgelt anders aus als externe akteure mit niedrigem netzentgelt. Warum wird der Faktor Grid Fee gemittelt werden, die erzeugerkosten aka ask_price ohne grid fee aber nicht. Diese kosten fallen doch auch nur anteilig an.

**Comment by FC4R** [comment]
und wie stehst du zum clearing preis von 0.0414 in cluster1 ? Da es den Profit des asks nicht betrifft wieviel netzentgelte der bid zahlt müsste das doch nachträglich berechnet werden können, oder?

**Comment by j-ti** [comment]
Ich bin gerade bei einer Implementierung für die grid_fees

**Comment by j-ti** [comment]
@FC4R Habe jetzt eine Implementierung ([feature/best_matching_gridfee_partition](https://github.com/BESTenergytrade/simply/compare/feature/best_matching_gridfee_partition)), die ich nochmal reviewen und checken muss, die für das Beispiel folgendes rausbekommt:
```
{'time': 0, 'bid_id': 1, 'ask_id': 4, 'bid_actor': 'buyer_c1_1', 'ask_actor': 'seller_c1_2', 'bid_cluster': 0, 'ask_cluster': 1, 'energy': 0.21000000000000005, 'price': 0.04602702702702703, 'included_grid_fee': 0.003}
{'time': 0, 'bid_id': 2, 'ask_id': 4, 'bid_actor': 'buyer_c1_3', 'ask_actor': 'seller_c1_2', 'bid_cluster': 1, 'ask_cluster': 1, 'energy': 0.060000000000000005, 'price': 0.04142857142857143, 'included_grid_fee': 0}
{'time': 0, 'bid_id': 1, 'ask_id': 3, 'bid_actor': 'buyer_c1_1', 'ask_actor': 'seller_MM', 'bid_cluster': 0, 'ask_cluster': None, 'energy': 0.16, 'price': 0.04602702702702703, 'included_grid_fee': 0.01}
{'time': 0, 'bid_id': 2, 'ask_id': 3, 'bid_actor': 'buyer_c1_3', 'ask_actor': 'seller_MM', 'bid_cluster': 1, 'ask_cluster': None, 'energy': 0.01, 'price': 0.04142857142857143, 'included_grid_fee': 0.01}
```

**Comment by FC4R** [comment]
> ich bin mir nicht sicher ob es funktioniert die grid fee einfach über den clearing price zu averagen. Beispiel Bid Cluster 1 Matches mit je einer energieeinheit Bid Price, Ask Price, Included_Grid fee 5, 1.0, 0.0 4, 2.5, 0.0 3, 3.0, 2.4 das dritte match wird durch das teure Netzentgelt dominiert. Die average grid fee wäre hier 0.8 = 1/3 * 2.4 wenn jetzt der clearing price auf 3- 0.8 = 2.2 gesetzt wird, reicht das nicht um den ask von 2.5 zu bezahlen. Wie wäre hier das vorgehen? aus sicht der lokalen akteure wirken sich dann externe akteure mit hohem netzentgelt anders aus als externe akteure mit niedrigem netzentgelt. Warum wird der Faktor Grid Fee gemittelt werden, die erzeugerkosten aka ask_price ohne grid fee aber nicht. Diese kosten fallen doch auch nur anteilig an.

2. Warum grid fees mitteln und erzeugerkosten nicht: die entscheidung resultiert daraus was man anreizen möchte. für die erzeugerkosten wurde der einheitliche clearing preis gewählt um anlagen mit günstigerer technologie mehr profit zu ermöglichen. dies soll zu mehr investitionen in diese technologien führen und somit mittelbar preise senken. 
Bei den netzentgelten sehe ich keine logischen grund mehrkosten in kauf zu nehmen. 
1. Das Problem, dass mit gemittelten netzentgelten im nachhinein nicht mehr gewährleistet ist, dass die bids größer sind als ask+netzentgelt, gibt es glaube ich nicht. Die bids sind anders als in deinem Beispiel immer von groß nach klein geordnet, d.h. wenn das unterste bid einen Preis zahlen kann, dann können es auch alle darüber. True?

**Comment by PaulScheerRLI** [comment]
> > ich bin mir nicht sicher ob es funktioniert die grid fee einfach über den clearing price zu averagen. Beispiel Bid Cluster 1 Matches mit je einer energieeinheit Bid Price, Ask Price, Included_Grid fee 5, 1.0, 0.0 4, 2.5, 0.0 3, 3.0, 2.4 das dritte match wird durch das teure Netzentgelt dominiert. Die average grid fee wäre hier 0.8 = 1/3 * 2.4 wenn jetzt der clearing price auf 3- 0.8 = 2.2 gesetzt wird, reicht das nicht um den ask von 2.5 zu bezahlen. Wie wäre hier das vorgehen? aus sicht der lokalen akteure wirken sich dann externe akteure mit hohem netzentgelt anders aus als externe akteure mit niedrigem netzentgelt. Warum wird der Faktor Grid Fee gemittelt werden, die erzeugerkosten aka ask_price ohne grid fee aber nicht. Diese kosten fallen doch auch nur anteilig an.
> 
>     2. Warum grid fees mitteln und erzeugerkosten nicht: die entscheidung resultiert daraus was man anreizen möchte. für die erzeugerkosten wurde der einheitliche clearing preis gewählt um anlagen mit günstigerer technologie mehr profit zu ermöglichen. dies soll zu mehr investitionen in diese technologien führen und somit mittelbar preise senken.
>        Bei den netzentgelten sehe ich keine logischen grund mehrkosten in kauf zu nehmen.


Bei den netzentgelten sehe ich den logischen Grund, dass die direkt durchgereichten grid fees, lokale energieerzeugung fördern, da der standortvorteil im vollen maß und nicht nur gemittelt auf sie wirkt

**Comment by FC4R** [comment]
das wird aber unfair, weil dann der ganze vorteil von lokalem Handel beim Verkäufer verbleibt und der käufer zahlt immer market maker Preise + volles Netzentgelt?

**Comment by FC4R** [comment]
> > 3. Das Problem, dass mit gemittelten netzentgelten im nachhinein nicht mehr gewährleistet ist, dass die bids größer sind als ask+netzentgelt, gibt es glaube ich nicht. Die bids sind anders als in deinem Beispiel immer von groß nach klein geordnet, d.h. wenn das unterste bid einen Preis zahlen kann, dann können es auch alle darüber. True?
> 
> Ja das Beispiel von Paul hat die grid_fees auch abgezogen, ich habe es nun so implementiert, dass die grid_fees oberhalb des letzten netto ask Preises liegen. Dennoch bin ich dabei die Merit order zu prüfen. Es ist nicht ganz eindeutig ob netto_preis + grid_fee für die merit order entscheident ist, denn der tatsächliche Einfluss auf den Clearing Preis ist geringer und sogar abhängig von der gematchten Menge.

"ich habe es nun so implementiert, dass die grid_fees oberhalb des letzten netto ask Preises liegen"  ich verstehe das nicht ganz??? 
Die bids müssen immer brutto sein und auch so geordnet werden, da es dem Käufer bei einer Preisobergrenze nicht darauf ankommt wie sich die Komponenten dann aufteilen, er ist bereit 10ct zu zahlen... Die aks müssen netto sein, weil es dem Verkäufer egal ist wieviele Nebenkosten anfallen, er will netto z.B. 5ct haben. Daher müssen brutto bids und netto asks + netzentgelten gelistet werden. d'accord? Passiert das so?

**Comment by j-ti** [comment]
So wie in dem Miro board abgestimmt, bezieht sich die Beschreibung auf den Effekt den ein ask mit grid-fees auf den Clearing Preis haben, nicht wie er dann abgerechnet wird.

**Comment by j-ti** [comment]
described matching error resolved, but still getting `"Matched energy does not match planned energy."` warning sometimes
