### ISSUE TITLE
"time" Überschrift in matches.csv und order.csv

### ISSUE THREAD

**Issue by FC4R** [BESTenergytrade/simply#221]
In den Ergebnisdateien gibt es die Spalte "time". In dieser Spalte werden aber nicht Zeiten sondern wahrscheinich zeitschritte eingetragen.
ToDo
1. unter der Überschrift "time" die Zeit laut Szenario angeben
2. eine Überschrift time_step einführen und dort die Daten angeben die jetzt unter "time" stehen

**Comment by j-ti** [comment]
In Szenarien die mit build_scenario erstellt werden, werden die Zeiten aktuell nicht übernommen. Simply kann aber auch mit Timestemps als index umgehen, enforciert dies aber nicht.

**Comment by j-ti** [comment]
duplicate of #168
