### ISSUE TITLE
Actor.get_market_schedule() defaulting to strategy 0

### ISSUE THREAD

**Issue by Emm-Zett** [BESTenergytrade/simply#234]
https://github.com/BESTenergytrade/simply/blob/ada5f7b0bd12a95ebc93d22fbb1b34d2cf97d695/simply/actor.py#L271C1-L271C37

If I am not mistaken, according to the warning text above, this line should be `strategy = 0`, right?

**Comment by j-ti** [comment]
Correct this would be better. I will change it

**Comment by j-ti** [comment]
solved in dev
