### ISSUE TITLE
Rename simply folder with code to source

### ISSUE THREAD

**Issue by stefansc1** [BESTenergytrade/simply#47]
This helps to avoid confusion and makes importing more sane.

**Comment by FC4R** [comment]
@stefansc1 what did you mean by this and would it still be usefull?

**Comment by stefansc1** [comment]
Our package is called simply and the code directory is also called simply. On occasion, this resulted in  imports like `from simply import simply`. Also, it could happen that the wrong simply directory was imported.
I agree with Timo that this is wontfix, as it is convention to name the code directory the same as the package. After installing, this actually makes the code more readable, as you're just importing (code-) simply: `from simply import market_wrapper` (in contrast to the more ambiguous `from source import ...`)

**Comment by FC4R** [comment]
but what about "from simpy-src import" or we name the other project simply-toolbox oä (or "from theBEST import") ??? I dont like simply/simply at all!
