### ISSUE TITLE
Grid fee matrix generated from network weights is always symmetrical

### ISSUE THREAD

**Issue by j-ti** [BESTenergytrade/simply#95]
Currently we only consider symmetric grid fee matrix. However it makes a difference to the grid in which direction energy is traded. A high power flow between two zones A->B with a risk of congestion, might be intensified by an additional flow due to traded energy in that direction, whereas a trade in the other direction B->A may even cause a relieving effect on the congestion.

**Comment by FC4R** [comment]
@j-ti, Is it true that we consider the grid fee to be symmetric? If not this issue can be closed if true it needs to be changed!

**Comment by j-ti** [comment]
Solution: Will be solved together with the introduction of dynamic grid fee setting, by providing a file with list of grid fee matrices
